SistemaInventario/Areas/Inventario/Controllers/CarroController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SistemaInventario.AccesoDatos.Repositorio.IRepositorio;
using SistemaInventario.Modelos;
using SistemaInventario.Modelos.ViewModels;
using SistemaInventario.Utilidades;
using System.Security.Claims;

namespace SistemaInventario.Areas.Inventario.Controllers
{
    [Area("Inventario")]//siempre debemos indicarle el atributo del area a la que pertence
    public class CarroController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        public CarroController(IUnidadTrabajo unidadTrabajo)//siempre debemos inyectar la unidad de trabajo
        {
            _unidadTrabajo = unidadTrabajo;
        }

        [BindProperty]//para poder usar e instanciar el objeto CarroComprasVM en la vista
        public CarroComprasVM CarroComprasVM { get; set; }

        [Authorize]// le indicamos que solo los usuarios logueados puedan acceder a esta vista
        public async Task<IActionResult> Index()
        {
            //capturo al usuario conectado
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            CarroComprasVM = new CarroComprasVM();
            CarroComprasVM.Orden = new Modelos.Orden();
            CarroComprasVM.CarroCompraLista = await _unidadTrabajo.CarroCompra.ObtenerTodos(u => u.UsuarioAplicacionId == claim.Value,
                                                                                            incluirPropiedades: "Producto");

            CarroComprasVM.Orden.TotalOrden = 0;
            CarroComprasVM.Orden.UsuarioAplicacionId = claim.Value;

            foreach (var lista in CarroComprasVM.CarroCompraLista)
            {
                lista.Precio = lista.Producto.Precio;//siempre muestra el precio actual del producto
                CarroComprasVM.Orden.TotalOrden += (lista.Precio * lista.Cantidad);
            }

            return View(CarroComprasVM);
        }

        [Authorize]
        public async Task<IActionResult> mas(int carroId)
        {
            var carroCompras = await _unidadTrabajo.CarroCompra.ObtenerPrimero(c => c.Id == carroId);//obtenemos el carro de compras
            carroCompras.Cantidad += 1;//aumentamos la cantidad
            await _unidadTrabajo.Guardar();
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> menos(int carroId)
        {
            var carroCompras = await _unidadTrabajo.CarroCompra.ObtenerPrimero(c => c.Id == carroId);//obtenemos el carro de compras
            if (carroCompras.Cantidad == 1)//si la cantidad es 1 hay que remover el registro
            {
                //removemos el registro y actualizamos la sesion
                var carroLista = await _unidadTrabajo.CarroCompra.ObtenerTodos(u => u.UsuarioAplicacionId == carroCompras.UsuarioAplicacionId);//obtenemos la lista de carros de compras del usuario
                var numeroProductos = carroLista.Count();
                _unidadTrabajo.CarroCompra.Remover(carroCompras.Id);
                await _unidadTrabajo.Guardar();

                HttpContext.Session.SetInt32(DS.ssCarroCompras, numeroProductos - 1);
            }
            else
            {
                carroCompras.Cantidad -= 1;//disminuimos la cantidad
                await _unidadTrabajo.Guardar();

            }

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> remover(int carroId)
        {
            //Remueve el registro del carro de compras y actualiza la sesion
            var carroCompras = await _unidadTrabajo.CarroCompra.ObtenerPrimero(c => c.Id == carroId);//obtenemos el carro de compras
                                                                                                     //removemos el registro y actualizamos la sesion
            var carroLista = await _unidadTrabajo.CarroCompra.ObtenerTodos(u => u.UsuarioAplicacionId == carroCompras.UsuarioAplicacionId);//obtenemos la lista de carros de compras del usuario
            var numeroProductos = carroLista.Count();
            _unidadTrabajo.CarroCompra.Remover(carroCompras.Id);
            await _unidadTrabajo.Guardar();

            HttpContext.Session.SetInt32(DS.ssCarroCompras, numeroProductos - 1);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Proceder()
        {
            var claimIdentidad = (ClaimsIdentity)User.Identity;
            var claim = claimIdentidad.FindFirst(ClaimTypes.NameIdentifier);

            CarroComprasVM = new CarroComprasVM()
            {
                Orden = new Modelos.Orden(),
                CarroCompraLista = await _unidadTrabajo.CarroCompra.ObtenerTodos(c => c.UsuarioAplicacionId == claim.Value, incluirPropiedades: "Producto"),
                Compania = await _unidadTrabajo.Compania.ObtenerPrimero(),

            };
            CarroComprasVM.Orden.TotalOrden = 0;
            CarroComprasVM.Orden.UsuarioAplicacion = await _unidadTrabajo.UsuarioAplicacion.ObtenerPrimero(u => u.Id == claim.Value);

            foreach (var lista in CarroComprasVM.CarroCompraLista)
            {
                lista.Precio = lista.Producto.Precio;//siempre muestra el precio actual del producto
                CarroComprasVM.Orden.TotalOrden += (lista.Precio * lista.Cantidad);
            }

            //obtengo los datos navegando por las propiedades de los objetos orden que esta en carrocomprasVM
            CarroComprasVM.Orden.NombresCliente = CarroComprasVM.Orden.UsuarioAplicacion.Nombres + " " + CarroComprasVM.Orden.UsuarioAplicacion.Apellidos;
            CarroComprasVM.Orden.Telefono = CarroComprasVM.Orden.UsuarioAplicacion.PhoneNumber;
            CarroComprasVM.Orden.Direccion = CarroComprasVM.Orden.UsuarioAplicacion.Direccion;
            CarroComprasVM.Orden.Ciudad = CarroComprasVM.Orden.UsuarioAplicacion.Ciudad;
            CarroComprasVM.Orden.Pais = CarroComprasVM.Orden.UsuarioAplicacion.Pais;

            //CONTROLAR EL STOCK
            foreach(var lista in CarroComprasVM.CarroCompraLista    )
            {
                //capturar el Stock de cada POroducto
                var producto = await _unidadTrabajo.BodegaProducto.ObtenerPrimero(p => p.ProductoId == lista.ProductoId && p.BodegaId== CarroComprasVM.Compania.BodegaVentaId );
                if (lista.Cantidad > producto.Cantidad)
                {
                    TempData[DS.Error]= "Error: La Cantidad del Producto " + lista.Producto.Descripcion + " solicitada, Exede alStock actual ( "+producto.Cantidad+" )";
                    return RedirectToAction("Index");
                }
            }
                return View(CarroComprasVM);

        }

    }
}

SistemaInventario/Areas/Inventario/Views/Carro/Index.cshtml
@model SistemaInventario.Modelos.ViewModels.CarroComprasVM
@using SistemaInventario.Utilidades

<div class="container">

    <form method="post">
        <br />
        @if (Model.CarroCompraLista.Count() > 0)
        {
            <div>
                <div class="container">
                    <div class="card">
                        <div class="card-header bg-dark text-light ml-0 row ">
                            <div class="col-6">
                                <i class="bi bi-cart-check-fill"></i> &nbsp;
                                Carro de Compras
                            </div>

                        </div>
                        <div class="card-body">
                            @foreach (var item in Model.CarroCompraLista)
                            {
                                <div class="row">
                                    <div class="d-none d-lg-block col-lg-1 text-center py-2">
                                        <img src="@DS.ImagenRuta@item.Producto.ImagenUrl" class="rounded" width="100" />
                                    </div>
                                    <div class="col-12 text-sm-center col-lg-6 text-lg-left">
                                        <h5><strong>@item.Producto.Descripcion</strong></h5>
                                    </div>
                                    <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                        <div class="col-4 text-md-right" style="padding-top:5px;">
                                            <h6><strong>$@item.Producto.Precio<span class="text-muted">x</span> @item.Cantidad </strong></h6>
                                        </div>
                                        <div class="col-6 col-sm-4 col-lg-6">
                                            <div class="float-right mx-1 mb-1">
                                                <a asp-action="mas" asp-route-carroId="@item.Id" class="btn btn-outline-primary">
                                                    <i class="bi bi-plus-square-fill"></i>
                                                </a>
                                            </div>
                                            <div class="float-right mx-1">
                                                <a asp-action="menos" asp-route-carroId="@item.Id" class="btn btn-outline-danger">
                                                    <i class="bi bi-dash-square-fill"></i>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-2 col-sm-4 col-lg-2 text-right">
                                            <a asp-action="remover" asp-route-carroId="@item.Id" class="btn btn-outline-danger">
                                                <i class="bi bi-trash-fill"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <hr />
                            }

                            <div class="row">
                                <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                                    <ul class="list-group">
                                        <li class="list-group-item d-flex justify-content-between bg-light">
                                            <span class="text-primary"> Total (USD)</span>
                                            <strong class="text-primary">$ <span id="txtTotalOrden">@Model.Orden.TotalOrden</span></strong>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <div class="card-footer row">

                                <div class="col-sm-12 col-lg-4 col-md-6 offset-lg-8 offset-md-6 ">

                                    <a asp-area="Inventario" asp-controller="Carro" asp-action="Proceder" class="btn btn-success form-control">Terminar Compra</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="col-12  p-0">
            <h3 class="text-primary text-center"><i class="bi bi-cart-check-fill"></i></h3>
        </div>
        <div class="col-12 p-2">
            @if (Model.CarroCompraLista.Count() == 0)
            {
                <h3 class="text-primary text-center">No hay Datos para Mostrar</h3>
            }

            <div class="text-center border-0">
                <a asp-area="Inventario" asp-controller="Home" asp-action="Index" class="btn btn-outline-primary ">Seguir Comprando</a>
            </div>

        </div>

    </form>





</div>

SistemaInventario/Areas/Inventario/Views/Carro/Proceder.cshtml
@model SistemaInventario.Modelos.ViewModels.CarroComprasVM

<div class="container">
    <form method="post">
        <br />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Detalles de la Orden
                        </div>

                    </div>
                    <div class="card-body">
                        <div class="container rounded p-2">
                            <div class="row">
                                <div class="col-12 col-lg-6 pb-4">
                                    <div class="row">
                                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                                            <span class="text-success">Detalles de Envío:</span>
                                        </h4>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Nombres</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="Orden.NombresCliente" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Telefono</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="Orden.Telefono" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Direccion</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="Orden.Direccion" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Ciudad</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="Orden.Ciudad" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Pais</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="Orden.Pais" type="text" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-lg-5 offset-lg-1">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-success">Productos:</span>
                                    </h4>
                                    <ul class="list-group mb-3">
                                        @foreach (var item in Model.CarroCompraLista)
                                        {
                                            <li class="list-group-item d-flex justify-content-between">
                                                <div>
                                                    <h6 class="my-0">@item.Producto.Descripcion</h6>
                                                    <small class="text-muted">Cantidad: @item.Cantidad</small>
                                                </div>
                                                <span class="text-muted">$ @(item.Producto.Precio * item.Cantidad)</span>
                                            </li>
                                        }

                                        <li class="list-group-item d-flex justify-content-between bg-light">
                                            <strong class="text-success">Total (USD)</strong>
                                            <strong class="text-success">$@(Model.Orden.TotalOrden)</strong>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12 col-md-8 pt-2">
                                <p class="text-success">Fecha Estimada de Envío: @DateTime.Now.AddDays(7).ToShortDateString() - @DateTime.Now.AddDays(14).ToShortDateString()</p>
                            </div>
                            <div class="col-12 col-md-4">

                                <button type="submit" value="Realizar Pedido" class="btn btn-success form-control">Realizar Pedido</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12  p-0">
            <h3 class="text-success text-center"><i class="bi bi-cart-check-fill"></i></h3>
        </div>
        <div class="col-12 p-1">
            <div class="text-center border-0">
                <a asp-area="Inventario" asp-controller="Carro" asp-action="Index" class="btn btn-outline-success ">Regresar al Carro</a>
            </div>

        </div>
    </form>

</div>